export default {
  AttackingEventsZoneA: { name: 'AttackingEventsZoneA', type: 'positive' },
  AttackingEventsZoneB: { name: 'AttackingEventsZoneB', type: 'positive' },
  AttackingEventsZoneC: { name: 'AttackingEventsZoneC', type: 'positive' },
  AttackingEventsZoneD: { name: 'AttackingEventsZoneD', type: 'positive' },
  BallPossessionLast10Mins: {
    name: 'BallPossessionLast10Mins',
    type: 'positive',
  },
  BallWonZoneA: { name: 'BallWonZoneA', type: 'positive' },
  BallWonZoneB: { name: 'BallWonZoneB', type: 'positive' },
  BallWonZoneC: { name: 'BallWonZoneC', type: 'positive' },
  BallWonZoneD: { name: 'BallWonZoneD', type: 'positive' },
  CarriesCrossedGainLine: { name: 'CarriesCrossedGainLine', type: 'positive' },
  CarriesKickReturn: { name: 'CarriesKickReturn', type: 'positive' },
  CarriesKickReturnMetres: {
    name: 'CarriesKickReturnMetres',
    type: 'positive',
  },
  CarriesMetres: { name: 'CarriesMetres', type: 'positive' },
  CarriesNotMadeGainLine: { name: 'CarriesNotMadeGainLine', type: 'negative' },
  CarriesOneOutDrive: { name: 'CarriesOneOutDrive', type: 'positive' },
  CarriesOneOutDriveMetres: {
    name: 'CarriesOneOutDriveMetres',
    type: 'positive',
  },
  CarriesPickAndGo: { name: 'CarriesPickAndGo', type: 'positive' },
  CarriesPickAndGoMetres: { name: 'CarriesPickAndGoMetres', type: 'positive' },
  CarriesSupport: { name: 'CarriesSupport', type: 'positive' },
  CarriesSupportMetres: { name: 'CarriesSupportMetres', type: 'positive' },
  CarryDominant: { name: 'CarryDominant', type: 'positive' },
  CarryIneffective: { name: 'CarryIneffective', type: 'negative' },
  CarryNeutral: { name: 'CarryNeutral', type: 'negative' },
  CleanBreaks: { name: 'CleanBreaks', type: 'positive' },
  CollectionFailed: { name: 'CollectionFailed', type: 'negative' },
  CollectionFromKick: { name: 'CollectionFromKick', type: 'positive' },
  CollectionInterception: { name: 'CollectionInterception', type: 'positive' },
  CollectionLooseBall: { name: 'CollectionLooseBall', type: 'positive' },
  CollectionSuccess: { name: 'CollectionSuccess', type: 'positive' },
  Conversions: { name: 'Conversions', type: 'positive' },
  DefendersBeaten: { name: 'DefendersBeaten', type: 'positive' },
  DominantTackles: { name: 'DominantTackles', type: 'positive' },
  DropGoals: { name: 'DropGoals', type: 'positive' },
  FreeKickConceded: { name: 'FreeKickConceded', type: 'negative' },
  FreeKickConcededAtLineout: {
    name: 'FreeKickConcededAtLineout',
    type: 'negative',
  },
  FreeKickConcededAtScrum: {
    name: 'FreeKickConcededAtScrum',
    type: 'negative',
  },
  Goals: { name: 'Goals', type: 'positive' },
  KickChargedDown: { name: 'KickChargedDown', type: 'negative' },
  KickFromHandMetres: { name: 'KickFromHandMetres', type: 'positive' },
  KickInTouch: { name: 'KickInTouch', type: 'positive' },
  KickOppnCollection: { name: 'KickOppnCollection', type: 'positive' },
  KickOutOfPlay: { name: 'KickOutOfPlay', type: 'negative' },
  KickPenaltyBad: { name: 'KickPenaltyBad', type: 'negative' },
  KickPenaltyGood: { name: 'KickPenaltyGood', type: 'positive' },
  KickPercentSuccess: { name: 'KickPercentSuccess', type: 'positive' },
  KickPossessionLost: { name: 'KickPossessionLost', type: 'negative' },
  KickPossessionRetained: { name: 'KickPossessionRetained', type: 'positive' },
  KickSuccess: { name: 'KickSuccess', type: 'positive' },
  KickTouchInGoal: { name: 'KickTouchInGoal', type: 'positive' },
  KickTryScored: { name: 'KickTryScored', type: 'ignore' },
  KicksFromHand: { name: 'KicksFromHand', type: 'positive' },
  Lineout3Man: { name: 'Lineout3Man', type: 'positive' },
  Lineout4Man: { name: 'Lineout4Man', type: 'positive' },
  Lineout5Man: { name: 'Lineout5Man', type: 'positive' },
  Lineout6Man: { name: 'Lineout6Man', type: 'positive' },
  LineoutFull: { name: 'LineoutFull', type: 'positive' },
  LineoutSuccess: { name: 'LineoutSuccess', type: 'positive' },
  LineoutThrowLostFreeKick: {
    name: 'LineoutThrowLostFreeKick',
    type: 'negative',
  },
  LineoutThrowLostHandlingError: {
    name: 'LineoutThrowLostHandlingError',
    type: 'negative',
  },
  LineoutThrowLostNotStraight: {
    name: 'LineoutThrowLostNotStraight',
    type: 'negative',
  },
  LineoutThrowLostOutright: {
    name: 'LineoutThrowLostOutright',
    type: 'negative',
  },
  LineoutThrowWonClean: { name: 'LineoutThrowWonClean', type: 'positive' },
  LineoutThrowWonFreeKick: {
    name: 'LineoutThrowWonFreeKick',
    type: 'positive',
  },
  LineoutThrowWonPenalty: { name: 'LineoutThrowWonPenalty', type: 'positive' },
  LineoutThrowWonTap: { name: 'LineoutThrowWonTap', type: 'positive' },
  LineoutWonOwnThrow: { name: 'LineoutWonOwnThrow', type: 'positive' },
  LineoutWonSteal: { name: 'LineoutWonSteal', type: 'positive' },
  LineoutsInfringeOpp: { name: 'LineoutsInfringeOpp', type: 'negative' },
  LineoutsInfringeOwn: { name: 'LineoutsInfringeOwn', type: 'negative' },
  LineoutsLost: { name: 'LineoutsLost', type: 'negative' },
  LineoutsToOppPlayer: { name: 'LineoutsToOppPlayer', type: 'negative' },
  LineoutsToOwnPlayer: { name: 'LineoutsToOwnPlayer', type: 'positive' },
  LineoutsWon: { name: 'LineoutsWon', type: 'positive' },
  MaulingMetres: { name: 'MaulingMetres', type: 'positive' },
  MaulsLost: { name: 'MaulsLost', type: 'negative' },
  MaulsLostOutright: { name: 'MaulsLostOutright', type: 'negative' },
  MaulsLostTurnover: { name: 'MaulsLostTurnover', type: 'negative' },
  MaulsTotal: { name: 'MaulsTotal', type: 'positive' },
  MaulsWon: { name: 'MaulsWon', type: 'positive' },
  MaulsWonOutright: { name: 'MaulsWonOutright', type: 'positive' },
  MaulsWonPenalty: { name: 'MaulsWonPenalty', type: 'positive' },
  MaulsWonPenaltyTry: { name: 'MaulsWonPenaltyTry', type: 'positive' },
  MaulsWonTry: { name: 'MaulsWonTry', type: 'positive' },
  Metres: { name: 'Metres', type: 'positive' },
  MissedConversions: { name: 'MissedConversions', type: 'negative' },
  MissedDropGoals: { name: 'MissedDropGoals', type: 'negative' },
  MissedPenalties: { name: 'MissedPenalties', type: 'negative' },
  MissedTackles: { name: 'MissedTackles', type: 'negative' },
  Offload: { name: 'Offload', type: 'positive' },
  Opposition22EntryOutcomeTurnover: {
    name: 'Opposition22EntryOutcomeTurnover',
    type: 'negative',
  },
  Passes: { name: 'Passes', type: 'positive' },
  PcKickPercent: { name: 'PcKickPercent', type: 'positive' },
  PcPossessionFirst: { name: 'PcPossessionFirst', type: 'positive' },
  PcPossessionSecond: { name: 'PcPossessionSecond', type: 'positive' },
  PcTerritoryFirst: { name: 'PcTerritoryFirst', type: 'positive' },
  PcTerritorySecond: { name: 'PcTerritorySecond', type: 'positive' },
  Penalties: { name: 'Penalties', type: 'positive' },
  PenaltiesConceded: { name: 'PenaltiesConceded', type: 'negative' },
  PenaltyConcededCollapsingMaul: {
    name: 'PenaltyConcededCollapsingMaul',
    type: 'negative',
  },
  PenaltyConcededDelibKnockOn: {
    name: 'PenaltyConcededDelibKnockOn',
    type: 'negative',
  },
  PenaltyConcededDissent: { name: 'PenaltyConcededDissent', type: 'negative' },
  PenaltyConcededEarlyTackle: {
    name: 'PenaltyConcededEarlyTackle',
    type: 'negative',
  },
  PenaltyConcededFoulPlay: {
    name: 'PenaltyConcededFoulPlay',
    type: 'negative',
  },
  PenaltyConcededHandlingInRuck: {
    name: 'PenaltyConcededHandlingInRuck',
    type: 'negative',
  },
  PenaltyConcededHighTackle: {
    name: 'PenaltyConcededHighTackle',
    type: 'negative',
  },
  PenaltyConcededKillingRuck: {
    name: 'PenaltyConcededKillingRuck',
    type: 'negative',
  },
  PenaltyConcededLineoutOffence: {
    name: 'PenaltyConcededLineoutOffence',
    type: 'negative',
  },
  PenaltyConcededObstruction: {
    name: 'PenaltyConcededObstruction',
    type: 'negative',
  },
  PenaltyConcededOffside: { name: 'PenaltyConcededOffside', type: 'negative' },
  PenaltyConcededOppHalf: { name: 'PenaltyConcededOppHalf', type: 'negative' },
  PenaltyConcededOther: { name: 'PenaltyConcededOther', type: 'negative' },
  PenaltyConcededOwnHalf: { name: 'PenaltyConcededOwnHalf', type: 'negative' },
  PenaltyConcededScrumOffence: {
    name: 'PenaltyConcededScrumOffence',
    type: 'negative',
  },
  PenaltyConcededWrongSide: {
    name: 'PenaltyConcededWrongSide',
    type: 'negative',
  },
  PenaltyKickForTouchMetres: {
    name: 'PenaltyKickForTouchMetres',
    type: 'positive',
  },
  PenaltyTries: { name: 'PenaltyTries', type: 'positive' },
  Points: { name: 'Points', type: 'positive' },
  Possession: { name: 'Possession', type: 'positive' },
  RedCards: { name: 'RedCards', type: 'negative' },
  RestartErrorNotTen: { name: 'RestartErrorNotTen', type: 'negative' },
  RestartErrorOutOfPlay: { name: 'RestartErrorOutOfPlay', type: 'negative' },
  RestartHalfway: { name: 'RestartHalfway', type: 'positive' },
  RestartOppError: { name: 'RestartOppError', type: 'positive' },
  RestartOppPlayer: { name: 'RestartOppPlayer', type: 'negative' },
  RestartOwnPlayer: { name: 'RestartOwnPlayer', type: 'positive' },
  RestartsLost: { name: 'RestartsLost', type: 'negative' },
  RestartsSuccess: { name: 'RestartsSuccess', type: 'positive' },
  RestartsWon: { name: 'RestartsWon', type: 'positive' },
  RetainedKicks: { name: 'RetainedKicks', type: 'ignore' },
  RuckBehindGainline: { name: 'RuckBehindGainline', type: 'negative' },
  RuckOnGainline: { name: 'RuckOnGainline', type: 'negative' },
  RuckOverGainline: { name: 'RuckOverGainline', type: 'positive' },
  RuckOverGainlinePercent: {
    name: 'RuckOverGainlinePercent',
    type: 'positive',
  },
  RuckSpeed03: { name: 'RuckSpeed03', type: 'positive' },
  RuckSpeed36: { name: 'RuckSpeed36', type: 'negative' },
  RuckSpeed6Plus: { name: 'RuckSpeed6Plus', type: 'negative' },
  RuckSuccess: { name: 'RuckSuccess', type: 'positive' },
  RucksLost: { name: 'RucksLost', type: 'negative' },
  RucksTotal: { name: 'RucksTotal', type: 'positive' },
  RucksWon: { name: 'RucksWon', type: 'positive' },
  Runs: { name: 'Runs', type: 'positive' },
  ScrumsLost: { name: 'ScrumsLost', type: 'negative' },
  ScrumsLostFreeKick: { name: 'ScrumsLostFreeKick', type: 'negative' },
  ScrumsLostOutright: { name: 'ScrumsLostOutright', type: 'negative' },
  ScrumsLostPenalty: { name: 'ScrumsLostPenalty', type: 'negative' },
  ScrumsReset: { name: 'ScrumsReset', type: 'negative' },
  ScrumsSuccess: { name: 'ScrumsSuccess', type: 'positive' },
  ScrumsTotal: { name: 'ScrumsTotal', type: 'positive' },
  ScrumsWon: { name: 'ScrumsWon', type: 'positive' },
  ScrumsWonFreeKick: { name: 'ScrumsWonFreeKick', type: 'positive' },
  ScrumsWonOutright: { name: 'ScrumsWonOutright', type: 'positive' },
  ScrumsWonPenalty: { name: 'ScrumsWonPenalty', type: 'positive' },
  ScrumsWonPenaltyTry: { name: 'ScrumsWonPenaltyTry', type: 'positive' },
  SetPieceWon: { name: 'SetPieceWon', type: 'positive' },
  TackleOffloadAllowed: { name: 'TackleOffloadAllowed', type: 'negative' },
  TacklePenaltyConceded: { name: 'TacklePenaltyConceded', type: 'negative' },
  TackleSuccess: { name: 'TackleSuccess', type: 'positive' },
  TackleTrySaver: { name: 'TackleTrySaver', type: 'positive' },
  TackleTurnover: { name: 'TackleTurnover', type: 'positive' },
  Tackles: { name: 'Tackles', type: 'positive' },
  Territory: { name: 'Territory', type: 'positive' },
  TerritoryLast10Mins: { name: 'TerritoryLast10Mins', type: 'positive' },
  TotalFreeKicksConceded: { name: 'TotalFreeKicksConceded', type: 'ignore' },
  TotalKicks: { name: 'TotalKicks', type: 'positive' },
  TotalKicksSucceeded: { name: 'TotalKicksSucceeded', type: 'positive' },
  TotalLineouts: { name: 'TotalLineouts', type: 'positive' },
  Tries: { name: 'Tries', type: 'positive' },
  TrueRetainedKicks: { name: 'TrueRetainedKicks', type: 'ignore' },
  TryAssists: { name: 'TryAssists', type: 'positive' },
  TryKicks: { name: 'TryKicks', type: 'positive' },
  TurnoverBadPass: { name: 'TurnoverBadPass', type: 'negative' },
  TurnoverCarriedInTouch: { name: 'TurnoverCarriedInTouch', type: 'negative' },
  TurnoverCarriedOver: { name: 'TurnoverCarriedOver', type: 'negative' },
  TurnoverForwardPass: { name: 'TurnoverForwardPass', type: 'negative' },
  TurnoverKickError: { name: 'TurnoverKickError', type: 'negative' },
  TurnoverKnockOn: { name: 'TurnoverKnockOn', type: 'negative' },
  TurnoverLostInRuckOrMaul: {
    name: 'TurnoverLostInRuckOrMaul',
    type: 'negative',
  },
  TurnoverOppHalf: { name: 'TurnoverOppHalf', type: 'positive' },
  TurnoverOwnHalf: { name: 'TurnoverOwnHalf', type: 'positive' },
  TurnoverWon: { name: 'TurnoverWon', type: 'ignore' },
  TurnoversWon: { name: 'TurnoversWon', type: 'positive' },
  YellowCards: { name: 'YellowCards', type: 'negative' },
};
