// Teamsheets for the current round
// starters / subs: last names as they appear in the official teamsheet
// "ou" alternatives are listed as separate entries so either player gets credit

export type Teamsheet = {
  starters: string[];
  subs: string[];
};

export const TEAMSHEETS: Record<string, Teamsheet> = {
  Bayonne: {
    starters: [
      "Orabé",
      "Tiberghien",
      "Martocq",
      "Tuilagi", "Mori",
      "Erbinartegaray",
      "Spring", "Segonds",
      "Germain",
      "Chouzenoux",
      "Capilla",
      "Fischer",
      "Paulos",
      "Iturria",
      "Tagi",
      "Bosch",
      "Bordelai",
    ],
    subs: [
      "Martin",
      "Cormenier",
      "Moon", "Ariceta",
      "Johnson",
      "Jantjies",
      "Segonds", "Spring",
      "Mori", "Tuilagi", "Hannoun",
      "Cotet",
    ],
  },
  "Bordeaux-Bègles": {
    starters: [
      "Mousquès",
      "Tambwe",
      "Uberti",
      "Drault",
      "Rayasi",
      "Reus",
      "Retière",
      "Matiu",
      "Gazzotti",
      "Vergnes-Taillefer",
      "Jacobs",
      "Swinton",
      "Falatea",
      "Barlot",
      "Boniface",
    ],
    subs: [
      "Sa",
      "Perchaud",
      "Zapedowski",
      "Bochaton",
      "Gardrat",
      "Lucu", "Hutteau",
      "Laharrague",
      "Sadie", "Tameifuna",
    ],
  },
  Castres: {
    starters: [
      "Palis",
      "Ambadiang",
      "Botitu",
      "Goodhue",
      "Vargas",
      "Hervé",
      "Arata",
      "Ramototabua",
      "Ardron",
      "Delaporte",
      "Vanverberghe",
      "Ducat",
      "Corato",
      "Durand",
      "Walcker",
    ],
    subs: [
      "Colonna",
      "Guérois-Galisson",
      "Maravat",
      "Cope",
      "Fernandez",
      "Cocagi",
      "Chabouni",
      "Collier",
    ],
  },
  Clermont: {
    starters: [
      "Hamdaoui", "Newsome",
      "Delguy", "Fall",
      "Loaloa",
      "Darricarrère",
      "Raka",
      "Plummer",
      "Jauneau",
      "Kremer",
      "Sowakula",
      "Hemery",
      "Ceyte",
      "Simmons",
      "Ojovan",
      "Massa",
      "Akhaladze",
    ],
    subs: [
      "Fourcade",
      "Lotrian",
      "Michaux",
      "Tixeront",
      "Muarua",
      "Zamora",
      "Newsome", "Hamdaoui",
      "Dzmanashvili",
    ],
  },
  "La Rochelle": {
    starters: [
      "West",
      "Nowell",
      "Lagivala",
      "Favre",
      "Leyds",
      "Hastoy",
      "Le Garrec",
      "Jegou",
      "Alldritt",
      "Pa. Boudehent",
      "Cancoriet",
      "Kante Samba",
      "Feao",
      "Latu",
      "Wardi",
    ],
    subs: [
      "Lespiaucq",
      "Kaddouri",
      "Haddad-Victor",
      "Bourgarit",
      "Timo",
      "Berjon",
      "Jurd",
      "Kuntelia",
    ],
  },
  Lyon: {
    starters: [
      "Méliande",
      "Mathiron",
      "Parisien",
      "Masi",
      "Wainiqolo",
      "Berdeu",
      "Cassang",
      "Allen",
      "Simmonds",
      "Cretin",
      "Guillard",
      "William",
      "Aptsiauri",
      "Marchand",
      "Kaabeche",
    ],
    subs: [
      "Chat",
      "Moukoro", "Marceline",
      "Roux",
      "Botha",
      "Saginadze",
      "Gonzalez",
      "Lorre",
      "Gomes Sa",
    ],
  },
  Montauban: {
    starters: [
      "Mouchous",
      "Vici",
      "Renda",
      "Mathy",
      "Vallée",
      "Fortunel",
      "Castel",
      "Ringuet",
      "Ma'afu",
      "Quercy",
      "Kanika",
      "Uanivi",
      "Mafileo",
      "Maurouard",
      "Bué",
    ],
    subs: [
      "Firmin",
      "Somkhishvili",
      "Bean",
      "Bitz",
      "Zabalza",
      "Jackson",
      "Reilhac",
      "Pomponio",
    ],
  },
  Montpellier: {
    starters: [
      "Banks",
      "Ngandebe",
      "Cadot",
      "Piccardo",
      "Taofifenua",
      "Miotti",
      "Price",
      "Bécognée",
      "B. Vunipola",
      "Nouchi",
      "Chalureau",
      "Verhaeghe",
      "Hounkpatin",
      "Uelese",
      "Erdocio",
    ],
    subs: [
      "C. Tolofua",
      "Forletta",
      "Beard",
      "Y. Camara",
      "Bernadet",
      "T. Vincent",
      "A. Vincent",
      "Haouas",
    ],
  },
  Pau: {
    starters: [
      "Maddocks",
      "Attissogbe",
      "Gailleton",
      "Brau-Boirie",
      "Grandidier-Nkanang",
      "Simmonds", "Despérès",
      "Robson",
      "Credoz",
      "Gorgadze",
      "Isa",
      "Maximin",
      "Auradou",
      "Laclayat",
      "Montoya",
      "Kaulashvili",
    ],
    subs: [
      "Rey", "Delhommel",
      "Sénéca",
      "Jolmes",
      "Capelli",
      "Zegueur",
      "Daubagna",
      "Simmonds", "Despérès",
      "Papidze",
    ],
  },
  Perpignan: {
    starters: [
      "Tedder",
      "J.-L. Joseph",
      "Buliruarua",
      "De la Fuente",
      "Forner",
      "Urdapilleta",
      "Hall",
      "Le Corvec",
      "Oviedo",
      "Chinarro",
      "Warion",
      "Yato",
      "Brookes",
      "Ruiz",
      "Devaux",
    ],
    subs: [
      "Montgaillard",
      "Beria",
      "Gray",
      "Van Tonder",
      "Aprasidze",
      "Aucagne",
      "Mascarenc",
      "Ceccarelli",
    ],
  },
  "Racing 92": {
    starters: [
      "Spring",
      "Hulleu",
      "Manu",
      "Fickou", "Habosi",
      "Naituvi",
      "Gibert",
      "Carbonneau",
      "Manyarara",
      "Hughes",
      "Baudonne",
      "Hill",
      "Lainault", "Tagitagivalu",
      "Bamba",
      "Tarrit",
      "Kharaishvili", "Gogichashvili",
    ],
    subs: [
      "Escobar",
      "Gogichashvili", "Kharaishvili",
      "Taofifenua",
      "Tagitagivalu", "Lainault",
      "Camara",
      "Seunes",
      "Tuisova",
      "Tupou",
    ],
  },
  "Stade français": {
    starters: [
      "Ibo",
      "Laloi",
      "Ezeala",
      "Néné", "Vili",
      "Etien",
      "Foursans-Bourdette",
      "Abadie",
      "Macalou",
      "Mapu", "Tanga",
      "Chapuis",
      "Pesenti",
      "Botha",
      "Melikidze", "P. Alo-Emile",
      "Garcia",
      "Païva", "M. Alo-Emile",
    ],
    subs: [
      "Peyresblanques",
      "M. Alo-Emile", "Païva",
      "Azagoh",
      "Tanga", "Mapu",
      "Hirigoyen", "Halaifonua",
      "Motassi",
      "Henry",
      "P. Alo-Emile", "Melikidze",
    ],
  },
  Toulon: {
    starters: [
      "Jaminet",
      "Ferté",
      "Smaïli",
      "Sinzelle",
      "Villière",
      "Garcia",
      "Serin",
      "E. Abadie",
      "Mercer",
      "Ju. Kpoku",
      "Javakhia",
      "Halagahu",
      "Gigashvili",
      "Lucchesi",
      "D. Brennan",
    ],
    subs: [
      "Damond",
      "Ametlla",
      "C. Mézou",
      "Shioshvili",
      "Coulon",
      "P. Garbisi",
      "Cowie",
      "Sorhaindo",
    ],
  },
  Toulouse: {
    starters: [
      "Remue",
      "Delibes",
      "Costes",
      "Chocobares",
      "Pouzelgues", "Lebel",
      "Kinghorn",
      "Graou",
      "Elías", "T. Ntamack",
      "Roumat",
      "Banos",
      "Meafou", "Vergé",
      "Brennan",
      "Merkler",
      "Marchand",
      "Baille",
    ],
    subs: [
      "Cramont", "Lacombre",
      "Mallez",
      "Vergé", "Meafou",
      "Flament", "T. Ntamack",
      "Willis", "Elías",
      "Dupont",
      "Ntamack", "Gourgues",
      "Ainu'u",
    ],
  },
};
