// Teamsheets for the current round
// starters / subs: last names as they appear in the official teamsheet
// "ou" alternatives are listed as separate entries so either player gets credit

export type Teamsheet = {
  starters: string[];
  subs: string[];
};

export const TEAMSHEETS: Record<string, Teamsheet> = {
  Bayonne: {
    starters: [
      "Orabé",
      "Tiberghien", "Erbinartegaray",
      "Maqala",
      "Tuilagi",
      "Carreras",
      "T. Spring", "Segonds",
      "Germain",
      "Chouzenoux", "Capilla",
      "Capilla", "Leota",
      "Bruni",
      "Paulos",
      "Iturria",
      "Tatafu",
      "Bosch", "Martin",
      "Bordelai",
    ],
    subs: [
      "Martin", "Bosch",
      "Castillon",
      "Leota",
      "Ariceta",
      "Jantjies", "Tilloles",
      "Segonds", "T. Spring",
      "Martocq",
      "Tagi", "Setiano",
    ],
  },
  "Bordeaux-Bègles": {
    starters: [
      "Rayasi", "Mousquès",
      "Tambwe",
      "Penaud",
      "Moefana",
      "Bielle-Biarrey",
      "Laharrague",
      "Lucu",
      "Woki",
      "Vergnes-Taillefer",
      "Bochaton",
      "Jacobs",
      "Palu",
      "Sadie",
      "Barlot",
      "Perchaud",
    ],
    subs: [
      "Sa",
      "Poirot",
      "Coleman",
      "Matiu",
      "Retière",
      "Janse Van Rensburg",
      "Uberti",
      "Tameifuna",
    ],
  },
  Castres: {
    starters: [
      "Palis",
      "Vargas",
      "Goodhue",
      "Cocagi",
      "Baget",
      "Popelin",
      "Fernandez",
      "Cope",
      "Papali'i",
      "Ramototabua",
      "Vanverberghe",
      "Maravat",
      "Corato",
      "Colonna",
      "Tichit",
    ],
    subs: [
      "Durand",
      "Guérois-Galisson",
      "Jedrasiak",
      "Tukino",
      "Doubrère",
      "Hervé",
      "Hulleu",
      "Azar",
    ],
  },
  Clermont: {
    starters: [
      "Hamdaoui",
      "Delguy",
      "Loaloa",
      "Simone", "Darricarrère",
      "Jurand",
      "Plummer",
      "Jauneau",
      "Kremer",
      "Sowakula",
      "Hémery",
      "Ceyte",
      "Simmons",
      "Ojovan",
      "Massa",
      "Lotrian",
    ],
    subs: [
      "Fourcade",
      "Falgoux", "Frisach",
      "Michaux",
      "Dessaigne",
      "Muarua",
      "Zamora",
      "Newsome",
      "Dzmanashvili",
    ],
  },
  "La Rochelle": {
    starters: [
      "Niniashvili",
      "Nowell",
      "Séguret",
      "Favre",
      "Leyds",
      "Hastoy",
      "Le Garrec",
      "Botia",
      "Haddad-Victor",
      "Cancoriet",
      "Skelton",
      "Kanté", "Samba",
      "Feao",
      "Lespiaucq-Brettes",
      "Wardi",
    ],
    subs: [
      "Sutidze",
      "Kaddouri",
      "Lavault",
      "Waqanisaravi",
      "Timo",
      "Berjon",
      "Lagivala",
      "Kuntelia",
    ],
  },
  Lyon: {
    starters: [
      "Lorre",
      "Wainiqolo",
      "Masi",
      "Millet",
      "Mathiron",
      "Méliande",
      "Cassang",
      "Botha",
      "Simmonds",
      "Cretin",
      "Guillard",
      "William",
      "Gomes Sa", "Aptsiauri",
      "Marchand",
      "Rey",
    ],
    subs: [
      "Chat",
      "Moukoro",
      "Roux",
      "Shvangiradze", "Parisien",
      "Okuya",
      "Gonzalez",
      "Berdeu",
      "Aptsiauri", "Maalo",
    ],
  },
  Montauban: {
    starters: [
      "Mouchous",
      "Vici",
      "Espeut",
      "Renda",
      "Vallée",
      "Bosviel",
      "Zabalza",
      "Ringuet",
      "Ma'afu",
      "Viiga",
      "Bean",
      "Uanivi",
      "Mafileo",
      "Maurouard",
      "Bué",
    ],
    subs: [
      "Jintcharadze",
      "Seyrolle",
      "Kaninka",
      "Bitz",
      "Coularis",
      "Castel",
      "Mathy",
      "Pomponio",
    ],
  },
  Montpellier: {
    starters: [
      "Echegaray",
      "Taofifenua",
      "A. Vincent",
      "Piccardo",
      "Rates",
      "T. Vincent",
      "Coly",
      "Bécognée",
      "Masibaka",
      "Tauleigne",
      "Chalureau",
      "Beard",
      "Haouas",
      "Riccitelli",
      "Erdocio",
    ],
    subs: [
      "Akrab",
      "Abuladze",
      "Uhila",
      "Camara",
      "Bernadet",
      "Martin",
      "Darmon",
      "Welsch",
    ],
  },
  Pau: {
    starters: [
      "Maddocks",
      "Attissogbe",
      "Gailleton",
      "Brau-Boirie",
      "Arfeuil", "Grandidier-Nkanang",
      "Simmonds",
      "Robson",
      "Credoz",
      "Isa",
      "Gorgadze",
      "Maximin",
      "Auradou",
      "Papidze",
      "Montoya", "Rey",
      "Kaulashvili",
    ],
    subs: [
      "Montoya", "Rey",
      "Bibi-Biziwu",
      "Capelli", "Jolmes",
      "Whitelock",
      "Zegueur",
      "Daubagna",
      "Desperes",
      "Laclayat",
    ],
  },
  Perpignan: {
    starters: [
      "Fahy",
      "Forner",
      "Buliruarua",
      "Mascarenc",
      "Forner",
      "Urdapilleta",
      "Ecochard",
      "Hicks",
      "Oviedo",
      "Van Tonder",
      "Warion",
      "Yato",
      "Ceccarelli",
      "Ruiz",
      "Tetrashvili",
    ],
    subs: [
      "Malolo",
      "Devaux",
      "Tuilagi",
      "Le Corvec",
      "Hall",
      "Allan",
      "Aucagne",
      "Roelofse",
    ],
  },
  "Racing 92": {
    starters: [
      "Spring",
      "Donguy", "Habosi",
      "Fickou",
      "Tuisova",
      "Ravutaumada",
      "Seunes",
      "Carbonneau",
      "Camara", "Diallo",
      "Tagitagivalu", "Hughes",
      "Baudonne",
      "Hill",
      "Rowlands",
      "Tupou", "Kharaishvili",
      "Tarrit",
      "Gogichashvili",
    ],
    subs: [
      "Escobar",
      "Kolingar",
      "Lainault",
      "Diallo",
      "Hughes", "Tagitagivalu",
      "Gibert",
      "Habosi", "Manu",
      "Kharaishvili", "Tupou",
    ],
  },
  "Stade français": {
    starters: [
      "Barré",
      "Marchant",
      "Ward",
      "Vili",
      "Dakuwaka",
      "Carbonel",
      "Kerr-Barlow",
      "Briatte",
      "Tanga-Mangene", "Macalou",
      "Halaifonua", "Scelzo",
      "Pesenti",
      "Azagoh",
      "Melikidze",
      "Nicotera",
      "M. Alo-Emile", "Païva",
    ],
    subs: [
      "Peyresblanques", "Garcia",
      "Païva", "M. Alo-Emile",
      "Turagacoke",
      "Scelzo", "Halaifonua",
      "Tanga-Mangene", "Macalou",
      "Abadie",
      "Néné",
      "P. Alo-Emile",
    ],
  },
  Toulon: {
    starters: [
      "Jaminet",
      "Ferté",
      "Brex",
      "Frisch",
      "Tuicuvu",
      "Albornoz",
      "White",
      "Abadie",
      "Shioshvili",
      "Ludlam",
      "Ribbans", "Alainu'uese",
      "Mézou",
      "Gigashvili",
      "Lucchesi",
      "Priso",
    ],
    subs: [
      "Damond",
      "Gros",
      "Halagahu",
      "Alainu'uese", "Javakhia", "Kpoku",
      "Coulon",
      "Domon",
      "Nonu",
      "Sinckler",
    ],
  },
  Toulouse: {
    starters: [
      "Kinghorn", "Ramos",
      "Thomas",
      "Chocobares",
      "Costes",
      "Lebel",
      "R. Ntamack",
      "Graou",
      "Banos",
      "Jelonch",
      "Willis",
      "Meafou",
      "Flament",
      "Merkler",
      "Cramont", "Lacombre",
      "Bertrand", "Ainu'u",
    ],
    subs: [
      "Lacombre", "Cramont",
      "Baille",
      "Brennan",
      "Roumat",
      "T. Ntamack",
      "Dupont",
      "Ramos", "Kinghorn",
      "Aldegheri",
    ],
  },
};
