// Teamsheets for the current round
// starters / subs: last names as they appear in the official teamsheet
// "ou" alternatives are listed as separate entries so either player gets credit,
// and each such entry is marked `uncertain: true` so the UI can flag them.

export type TeamsheetEntry = string | { name: string; uncertain?: boolean };

export type Teamsheet = {
  starters: TeamsheetEntry[];
  subs: TeamsheetEntry[];
};

export const entryName = (e: TeamsheetEntry): string =>
  typeof e === "string" ? e : e.name;

export const entryUncertain = (e: TeamsheetEntry): boolean =>
  typeof e === "string" ? false : !!e.uncertain;

const u = (name: string): TeamsheetEntry => ({ name, uncertain: true });

export const TEAMSHEETS: Record<string, Teamsheet> = {
  Bayonne: {
    starters: [
      "Orabé",
      u("Carreras"),
      u("Lévêque"),
      "Martocq",
      u("Mori"),
      u("Tuilagi"),
      "Erbinartegaray",
      "Spring",
      "Jantjies",
      "Iturria",
      "Capilla",
      u("Fischer"),
      u("Ariceta"),
      u("Marchesin"),
      "Moon",
      "Johnson",
      "Tagi",
      "Martin",
      "Cormenier",
    ],
    subs: [
      u("Giudicelli"),
      u("Errecart"),
      "Calles",
      "Paulos",
      u("Traversier"),
      u("Marchesin"),
      "Germain",
      u("Tuilagi"),
      u("Mori"),
      u("Lévêque"),
      u("Carreras"),
      "Cotet",
    ],
  },
  "Bordeaux-Bègles": {
    starters: [
      "Buros",
      u("Uberti"),
      u("Rayasi"),
      "Penaud",
      "Moefana",
      "Bielle-Biarrey",
      "Jalibert",
      "Lucu",
      "Woki",
      "Gazzotti",
      "Bochaton",
      "Coleman",
      "Palu",
      "Tameifuna",
      "Barlot",
      "Perchaud",
    ],
    subs: [
      "Lamothe",
      "Poirot",
      "Jacobs",
      u("Swinton"),
      u("Vergnes-Taillefer"),
      "Retière",
      "Reus",
      u("Rayasi"),
      u("Uberti"),
      "Sadie",
    ],
  },
  Castres: {
    starters: [
      "Palis",
      "Vargas",
      "Cocagi",
      "Goodhue",
      "Ambadiang",
      "Hervé",
      "Arata",
      "Babillot",
      "Ramototabua",
      "Delaporte",
      "Staniforth",
      "Ducat",
      "Corato",
      "Durand",
      "Guérois",
    ],
    subs: [
      "Colonna",
      "Walcker",
      "Maravat",
      "Vanverberghe",
      "Papali'i",
      "Fernandez",
      "Chabouni",
      "Chilachava",
    ],
  },
  Clermont: {
    starters: [
      "Hamdaoui",
      "Delguy",
      "Loaloa",
      u("Moala"),
      u("Darricarrère"),
      "Raka",
      "Plummer",
      "Jauneau",
      "Hemery",
      "Sowakula",
      "Tixeront",
      "Ceyte",
      u("Kremer"),
      u("Michaux"),
      "Tutisani",
      "Massa",
      u("Lotrian"),
      u("Akhaladze"),
    ],
    subs: [
      "Fourcade",
      u("Lotrian"),
      u("Akhaladze"),
      u("Kremer"),
      u("Michaux"),
      "Dessaigne",
      "Muarua",
      "Zamora",
      "Simone",
      "Ez Zahouany",
    ],
  },
  "La Rochelle": {
    starters: [
      "Niniashvili",
      "Nowell",
      "Lagivala",
      "Favre",
      "Leyds",
      "Hastoy",
      "Le Garrec",
      "Jegou",
      "Alldritt",
      "Pa. Boudehent",
      "Cancoriet",
      "Kante Samba",
      "Sclavi",
      "Latu",
      "Wardi",
    ],
    subs: [
      "Lespiaucq-Brettes",
      "Kaddouri",
      "Haddad-Victor",
      "Bourgarit",
      "Botia",
      "Berjon",
      u("West"),
      u("Jurd"),
      u("Seuteni"),
      "Sorin",
    ],
  },
  Lyon: {
    starters: [
      "Tchaptchet",
      "Wainiqolo",
      "Maraku",
      "Millet",
      "Ioane",
      "Berdeu",
      "Cassang",
      "William",
      "Simmonds",
      "Déliance",
      "Roux",
      "Guillard",
      "Aptsiauri",
      "Marchand",
      "Rey",
    ],
    subs: [
      "Sarragallet",
      "Moukoro",
      "Botha",
      "Cretin",
      "Allen",
      "Gonzalez",
      "Jackson",
      "Marceline",
    ],
  },
  Montauban: {
    starters: [
      "Mouchous",
      "Vici",
      "Jackson",
      "Renda",
      "Vallée",
      "Bosviel",
      "Castel",
      "Ringuet",
      "Viiga",
      "Quercy",
      "Bean",
      "Uanivi",
      "Pomponio",
      "Firmin",
      "Seyrolle",
    ],
    subs: [
      "Jintcharadze",
      "Bué",
      "Ma'afu",
      "Fifita",
      "Penetro",
      "Espeut",
      "Reilhac",
      "Mafileo",
    ],
  },
  Montpellier: {
    starters: [
      "Echegaray",
      "Banks",
      "A. Vincent",
      "Anyanwu",
      "Ngandebe",
      "Miotti",
      "Price",
      "Bécognée",
      "Vunipola",
      "Camara",
      "Duguid",
      "Verhaeghe",
      "Haouas",
      "Uelese",
      "Forletta",
    ],
    subs: [
      "Tolofua",
      "Erdocio",
      "Beard",
      "Tauleigne",
      "Diaby",
      "Bernadet",
      "T. Vincent",
      "Cadot",
      "Welsch",
    ],
  },
  Pau: {
    starters: [
      "Maddocks",
      "Attissogbe",
      "Gailleton",
      "Brau-Boirie",
      "Grandidier-Nkanang",
      "Simmonds",
      u("Daubagna"),
      u("Robson"),
      "Credoz",
      "Gorgadze",
      "Zegueur",
      "Maximin",
      "Auradou",
      "Laclayat",
      "Montoya",
      "Bibi-Biziwu",
    ],
    subs: [
      u("Rey"),
      u("Delhommel"),
      "Seneca",
      "Jolmes",
      "Picquette",
      "Isa",
      u("Daubagna"),
      u("Robson"),
      "Desperes",
      "Papidze",
    ],
  },
  Perpignan: {
    starters: [
      "Tedder",
      "Joseph",
      "Poulet",
      "De la Fuente",
      "Forner",
      "Urdapilleta",
      "Hall",
      "Van Tonder",
      "Oviedo",
      "Ritchie",
      "Gray",
      "Le Corvec",
      "Brookes",
      "Montgaillard",
      "Beria",
    ],
    subs: [
      "Ruiz",
      "Devaux",
      "Yato",
      "Hicks",
      "Aprasidze",
      "Aucagne",
      "Buliruarua",
      "Ceccarelli",
    ],
  },
  "Racing 92": {
    starters: [
      "Spring",
      "Hulleu",
      u("Fickou"),
      u("Habosi"),
      "Tuisova",
      "Naituvi",
      "Seunes",
      "Carbonneau",
      "Diallo",
      "Tagitagivalu",
      "Baudonne",
      "Lainault",
      "Hill",
      u("Tupou"),
      u("Kharaishvili"),
      "Tarrit",
      "Gogichashvili",
    ],
    subs: [
      "Basse",
      "Kolingar",
      "Taofifenua",
      "Hughes",
      "Camara",
      "Gibert",
      "Manu",
      "Bamba",
    ],
  },
  "Stade français": {
    starters: [
      "Barré",
      "Dakuwaqa",
      "Ward",
      "Vili",
      "Marchant",
      "Carbonel",
      "Kerr-Barlow",
      "Hirigoyen",
      "Tanga",
      "Briatte",
      "Azagoh",
      "Gabrillagues",
      "Paul Alo-Emile",
      "Nicotera",
      "M. Alo-Emile",
    ],
    subs: [
      "Peyresblanques",
      "Iscaro",
      "Pesenti",
      "Chapuis",
      "Macalou",
      "Abadie",
      u("Néné"),
      u("Ezeala"),
      "Melikidze",
    ],
  },
  Toulon: {
    starters: [
      u("Jaminet"),
      u("Garcia"),
      "Dréan",
      "Cowie",
      "Brex",
      "Ferté",
      "Garbisi",
      "Serin",
      u("Abadie"),
      u("Ollivon"),
      "Mercer",
      "Shioshvili",
      u("Javakhia"),
      u("Ribbans"),
      "Halagahu",
      "Sinckler",
      "Baubigny",
      "Gros",
    ],
    subs: [
      u("Damond"),
      u("Lucchesi"),
      "Ametlla",
      "Mézou",
      u("Coulon"),
      u("Ollivon"),
      u("Abadie"),
      "Albornoz",
      "White",
      "Frisch",
      u("Sorhaindo"),
      u("Gigashvili"),
    ],
  },
  Toulouse: {
    starters: [
      "Ramos",
      "Thomas",
      "Gourgues",
      "Chocobares",
      "Lebel",
      "R. Ntamack",
      "Dupont",
      "Willis",
      u("T. Ntamack"),
      u("Roumat"),
      "Cros",
      "Meafou",
      u("Flament"),
      u("Brennan"),
      "Merkler",
      "Mauvaka",
      "Bertrand",
    ],
    subs: [
      "Lacombre",
      "Baille",
      u("Brennan"),
      u("Flament"),
      "Elias",
      u("Roumat"),
      "Graou",
      "Costes",
      "Colombe",
    ],
  },
};
